### ISSUE TITLE
Plugin throws an "unsupported version" error despite me using a documented supported version

### ISSUE THREAD

**Issue by tt-thoma** [sub-kek/CustomDiscs-SVC#11]
## Using
> - Paper 1.21.3 (1.21.3-77-master@1e035f3)
> - [CustomDiscs-SVC Version 2.0.3 from Modrinth](https://modrinth.com/plugin/customdiscs-svc/version/2.0.3)

## Plugins list
*(yes it's bloated)*
 - AlixSystem (3.6.0 (Nightly-1))
 - BedHome (2.35)
 - Chunky (1.4.28)
 - CoreProtect (22.4)
 - **CustomDiscs (2.0.3)**
 - DiscordSRV (1.29.0)
 - Geyser-Recipe-Fix (1.5)
 - Geyser-Spigot (2.5.0-SNAPSHOT)
 - Hurricane (2.1-SNAPSHOT)
 - ImageFrame (1.7.11.0)
 - LuckPerms (5.4.146)
 - ProtocolLib (5.4.0-SNAPSHOT-736)
 - SkinsRestorer (15.4.4)
 - Tool-Trims (1.2)
 - XClaim (1.15.1)
 - floodgate (2.2.3-SNAPSHOT (b114-83fbd6e))
 - voicechat (2.5.25)
 - voicechat-discord (3.0.5)

## Expected behavior
The plugin should load normally, because it's said to be compatible with Minecraft 1.21.3

## Actual behavior
The plugin crashes on activation because "it's not compatible with Minecraft 1.21.3"

## Error message
```
[17:47:15 INFO]: [CustomDiscs] Loading server plugin CustomDiscs v2.0.3
[17:47:15 ERROR]: [CustomDiscs] Error initializing plugin 'CustomDiscs-2.0.3.jar' in folder 'plugins/.paper-remapped' (Is it up to date?)
io.github.subkek.customdiscs.libs.dev.jorel.commandapi.exceptions.UnsupportedVersionException: This version of Minecraft is unsupported: 1.21.3
        at CustomDiscs-2.0.3.jar/io.github.subkek.customdiscs.libs.dev.jorel.commandapi.CommandAPIVersionHandler.getPlatform(CommandAPIVersionHandler.java:71) ~[CustomDiscs-2.0.3.jar:?]
        at CustomDiscs-2.0.3.jar/io.github.subkek.customdiscs.libs.dev.jorel.commandapi.CommandAPI.onLoad(CommandAPI.java:112) ~[CustomDiscs-2.0.3.jar:?]
        at CustomDiscs-2.0.3.jar/io.github.subkek.customdiscs.CustomDiscs.onLoad(CustomDiscs.java:61) ~[CustomDiscs-2.0.3.jar:?]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[paper-1.21.3.jar:1.21.3-77-1e035f3]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[paper-1.21.3.jar:1.21.3-77-1e035f3]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[paper-1.21.3.jar:1.21.3-77-1e035f3]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40) ~[paper-1.21.3.jar:1.21.3-77-1e035f3]
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:561) ~[paper-1.21.3.jar:1.21.3-77-1e035f3]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:289) ~[paper-1.21.3.jar:1.21.3-77-1e035f3]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1235) ~[paper-1.21.3.jar:1.21.3-77-1e035f3]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:340) ~[paper-1.21.3.jar:1.21.3-77-1e035f3]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

Is it a bug or has the plugin just not been ported yet?

**Comment by sub-kek** [comment]
Fixed in 9db3d638abb3153142ed9268ad9d07f8694908fd
