### ISSUE TITLE
java.lang.InterruptedException: sleep interrupted

### ISSUE THREAD

**Issue by Trard** [sub-kek/CustomDiscs-SVC#2]
Sometimes plugin logs

[08:54:21] [LavaPlayer/ERROR]: [CustomDiscs] Error while playing disc:
java.lang.InterruptedException: sleep interrupted
        at java.lang.Thread.sleep0(Native Method) ~[?:?]
        at java.lang.Thread.sleep(Thread.java:558) ~[?:?]
        at java.util.concurrent.TimeUnit.sleep(TimeUnit.java:446) ~[?:?]
        at io.github.subkek.customdiscs.LavaPlayerManager$LavaPlayer.startTrackJob(LavaPlayerManager.java:178) ~[CustomDiscs-1.3.9(2).jar:?]
        
 However, I don't see any issues in game

**Comment by Trard** [comment]
> I need the output of /about.

![image](https://github.com/sub-kek/CustomDiscs-SVC/assets/68790724/e9ff7a7c-210e-49b3-805d-bb2a978c11f1)

**Comment by sub-kek** [comment]
Most likely the error occurs if you pull out a record while the track is loading. I will try to fix this in the nearest future.
