### ISSUE TITLE
Duplication Bug

### ISSUE THREAD

**Issue by DaddyRobLIVE** [sub-kek/CustomDiscs-SVC#9]
Error: [11:28:21 WARN]: [CustomDiscs] Task #8492174 for CustomDiscs v2.0.0 generated an exception
java.lang.ClassCastException: class org.bukkit.craftbukkit.block.CraftBlockState cannot be cast to class org.bukkit.block.Jukebox (org.bukkit.craftbukkit.block.CraftBlockState and org.bukkit.block.Jukebox are in unnamed module of loader java.net.URLClassLoader @41cf53f9)
        at CustomDiscs-2.0.0.jar/io.github.subkek.customdiscs.PhysicsManager.stop(PhysicsManager.java:66) ~[CustomDiscs-2.0.0.jar:?]
        at CustomDiscs-2.0.0.jar/io.github.subkek.customdiscs.PhysicsManager.lambda$start$0(PhysicsManager.java:85) ~[CustomDiscs-2.0.0.jar:?]
        at CustomDiscs-2.0.0.jar/io.github.subkek.customdiscs.libs.com.tcoded.folialib.impl.SpigotImplementation.lambda$runTimer$4(SpigotImplementation.java:161) ~[CustomDiscs-2.0.0.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:88) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-00d685c]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-00d685c]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1731) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-00d685c]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:490) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-00d685c]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1603) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-00d685c]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1309) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-00d685c]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:335) ~[sparklypaper-1.21.1.jar:1.21.1-DEV-00d685c]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
        
**Environment**
Fork: https://github.com/SparklyPower/SparklyPaper
Version: 2.0.0

**Reproduction Steps**
1. Install CD
2. Create a YT disc
3. Insert disc to a Jukebox
4. Remove the disc
5. Audio still plays
6. You can spam remove the disc from the jukebox and it won't stop (disc will just keep coming out)

**Comment by steepboy** [comment]
Fixed on lasted relises
